sudo: required
language: ruby
addons:
  apt:
    packages:
    - lftp
cache:
  directories:
    - bash
before_script:
  - whereis bash
  - ./spec/install_bash.sh
after_script:
  - cane --style-exclude 'spec/**/*.rb'
  - yard stats --list-undoc
os:
  - linux
rvm:
  - 2.4.0
matrix:
  include:
    - rvm: 2.4.0
      env: INSTALL_BASH_VERSION=sh BASHCOV_BASH_PATH=/bin/sh
  allow_failures:
    - os: osx
    - rvm: ruby-head
    - rvm: rbx-2
    - env: INSTALL_BASH_VERSION=4.0
    - env: INSTALL_BASH_VERSION=4.1
    - env: INSTALL_BASH_VERSION=sh
